/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Chelo
 */
public class Grafica extends javax.swing.JFrame {

    HiloContador hilito, hilito2;
    public static Object cerrojo = new Object();

    /**
     * Creates new form lol
     */
    public Grafica() {
        initComponents();

        hilito = new HiloContador(lbl1);
        hilito2 = new HiloContador(lbl2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_iniciar = new javax.swing.JButton();
        btn_hilo2 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnPausar1 = new javax.swing.JButton();
        btnPausar2 = new javax.swing.JButton();
        btnResumir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        btn_hilo2.setText("Hilo 2");
        btn_hilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hilo2ActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1.setText("------");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl2.setText("------");

        btnPausar1.setText("Pausar1");
        btnPausar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausar1ActionPerformed(evt);
            }
        });

        btnPausar2.setText("Pausar2");

        btnResumir1.setText("Resumir");
        btnResumir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hilo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPausar2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPausar1)
                        .addGap(35, 35, 35)
                        .addComponent(btnResumir1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPausar1)
                        .addComponent(btnResumir1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPausar2))
                    .addComponent(btn_hilo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        if (!hilito.isAlive()) {
            hilito.start();
        } else {
            System.out.println("No");
        }


    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void btn_hilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hilo2ActionPerformed
        if (!hilito2.isAlive()) {
            hilito2.start();
        } else {
            System.out.println("No");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btn_hilo2ActionPerformed

    private void btnPausar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausar1ActionPerformed

        hilito.detener();
    }//GEN-LAST:event_btnPausar1ActionPerformed

    private void btnResumir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumir1ActionPerformed
        // TODO add your handling code here:
        hilito.resumir();
    }//GEN-LAST:event_btnResumir1ActionPerformed

    public class HiloContador extends Thread {

        private JLabel lblUno;
        private Boolean detenido;

        public HiloContador(JLabel lblUno) {
            this.lblUno = lblUno;
        }

        @Override
        public void run() {
            int i = 0;
            while (true) {

                try {
                    detenido = false;
                    lblUno.setText("" + i);//conversion trucha
                    System.out.println(lblUno + ">" + i);
                    Thread.sleep(1000);
                    i++;

                    synchronized (cerrojo) {
                        if (detenido) {
                            try {
                                cerrojo.wait();
                            } catch (InterruptedException ex) {
                                Logger.getLogger(HiloContador.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        }

                    }

                } catch (InterruptedException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        

        

        public void detener() {
            detenido = true;
        }

        public void resumir() {

            synchronized (cerrojo) {
                detenido = false;
                cerrojo.notifyAll();
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausar1;
    private javax.swing.JButton btnPausar2;
    private javax.swing.JButton btnResumir1;
    private javax.swing.JButton btn_hilo2;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
